name: mqtt_client
description: A server and browser based MQTT client for Dart supporting normal, secure sockets and websockets.
version: 10.0.0
repository: https://github.com/shamblett/mqtt_client
homepage: https://github.com/shamblett/mqtt_client

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  typed_data: '^1.3.2'
  event_bus: '^2.0.0'
  path: '^1.8.2'
  crypto: '3.0.2'
  meta: '^1.9.1'

dev_dependencies:
  test: '^1.24.3'
  lints: '2.0.1'
  build_runner: '2.3.3'
  build_test: '^2.1.7'
  build_web_compilers: '3.2.7'
  http: '0.13.5'
  sigv4: '^5.0.0'
  mocktail: '^0.3.0'

false_secrets:
  - /test/pem/self_signed.key
  - /test/pem/localhost.key
